export const PROJECT_CATEGORIES = Object.freeze([
  'Artificial Intelligence',
  'Machine Learning',
  'Web Development',
  'Mobile Development',
  'Data Science',
  'Cybersecurity',
  'Internet of Things',
  'Embedded Systems',
  'Networking',
  'Cloud Computing',
  'Database Systems',
  'Computer Vision',
  'Natural Language Processing',
  'Robotics',
  'Bioinformatics',
  'Software Engineering',
  'Human-Computer Interaction',
  'Other',
]);
